### ISSUE TITLE
[FEATURE] - Make the Site Responsive

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#1]
- [x]  I agree to follow this project's Contributing Guidelines.

### Description
The current state of the site lacks responsiveness, and there is a need to make it adapt well to different screen sizes. 

### Proposed Solution
Migrate the site's styling from Bootstrap 5 to Tailwind CSS to achieve a more flexible and responsive design.

### Additional Context
The decision to move to Tailwind CSS is based on its utility in creating responsive and highly customizable user interfaces. This transition aligns with modern web development trends and will enhance the overall user experience. Additionally, consider evaluating potential challenges and benefits of this migration, and if there are specific areas of the site that require special attention regarding responsiveness.

### Steps to be taken
- Avoid keeping both bootstrap and tailwind together as they can create conflicts
- Add tailwind css to the dependencies(See tailwind doc for vite and react - https://tailwindcss.com/docs/guides/vite)
- Remove the classnames used which comes from bootstrap and add tailwind classes.
- After the complete migration remove the bootstarp from dependencies. (npm uninstall bootstrap)

## It is adviced to migrate the entire site from bootstrap to tailwind css

**Comment by ani2607** [comment]
@sd012gfhkhhvh would love to work over this issue. Please assign this to me under the JWOC TAG.

**Comment by sd012gfhkhhvh** [comment]
> @sd012gfhkhhvh would love to work over this issue. Please assign this to me under the JWOC TAG.

Sure @ani2607 , will assign to you tomorrow. But make sure you migrate the entire UI from bootstrap to tailwind css. Let me know your thoughts.

**Comment by ani2607** [comment]
> > @sd012gfhkhhvh would love to work over this issue. Please assign this to me under the JWOC TAG.
> 
> Sure @ani2607 , will assign to you tomorrow. But make sure you migrate the entire UI from bootstrap to tailwind css. Let me know your thoughts.

cool idea!!. But I need to clarify whether the code contain the bootstrap components or just its utility classes?

**Comment by sd012gfhkhhvh** [comment]
> > > @sd012gfhkhhvh would love to work over this issue. Please assign this to me under the JWOC TAG.
> > 
> > 
> > Sure @ani2607 , will assign to you tomorrow. But make sure you migrate the entire UI from bootstrap to tailwind css. Let me know your thoughts.
> 
> cool idea!!. But I need to clarify whether the code contain the bootstrap components or just its utility classes?

Try to completely remove any boostrap components present along with utility classes, as they can create conflicts in the future with tailwind css.  And kindly comment on the issue once again saying "Please assign this to me under the JWOC TAG" as You did it before 15th and its not gonna be counted for points as per guideline. made a fresh comment I will assign u the issue

**Comment by ani2607** [comment]
Please assign this to me under the JWOC TAG . would love to do.

**Comment by sd012gfhkhhvh** [comment]
> Please assign this to me under the JWOC TAG . would love to do.

assignning you the issue. keep me updated with your changes in the comment section. Now kindly go to the slateai chanel on discord and see the pinned message.

**Comment by ani2607** [comment]
@sd012gfhkhhvh As I haven't used the bootstrap in my develepment journey , I am struggling a lot to migrate from bootstrap to tailwind css . Therefore , I request you to please assign this issue to someone else .

**Comment by sd012gfhkhhvh** [comment]
> @sd012gfhkhhvh As I haven't used the bootstrap in my develepment journey , I am struggling a lot to migrate from bootstrap to tailwind css . Therefore , I request you to please assign this issue to someone else .

Are u sure? You dont need to be worry about bootstrap, u just need to remove the bootstrap classes and add tailwind classes instade. And the the end just uninstall the bootstrap dependency

**Comment by ani2607** [comment]
> > @sd012gfhkhhvh As I haven't used the bootstrap in my develepment journey , I am struggling a lot to migrate from bootstrap to tailwind css . Therefore , I request you to please assign this issue to someone else .
> 
> Are u sure? You dont need to be worry about bootstrap, u just need to remove the bootstrap classes and add tailwind classes instade. And the the end just uninstall the bootstrap dependency

yes!, I would love to contribute into another issue.

**Comment by sd012gfhkhhvh** [comment]
> > > @sd012gfhkhhvh As I haven't used the bootstrap in my develepment journey , I am struggling a lot to migrate from bootstrap to tailwind css . Therefore , I request you to please assign this issue to someone else .
> > 
> > 
> > Are u sure? You dont need to be worry about bootstrap, u just need to remove the bootstrap classes and add tailwind classes instade. And the the end just uninstall the bootstrap dependency
> 
> yes!, I would love to contribute into another issue.

Ok, I am unassigning.

**Comment by 0xMishra** [comment]
Can you please assign me this issue under JWOC

**Comment by sd012gfhkhhvh** [comment]
> Can you please assign me this issue under JWOC

assigning you the issue. keep me  updated about your changes.

**Comment by sd012gfhkhhvh** [comment]
Issue#1 got resolved and merged.
