### ISSUE TITLE
[BUG] - Github Logo is not visible

### ISSUE THREAD

**Issue by pranay911** [sd012gfhkhhvh/Slate.AI#13]
- [x]  I agree to follow this project's Contributing Guidelines.

**Severity:**
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

**Describe the Bug:**
The GitHub logo in the navigation bar shares the same black color as the background, making it initially invisible. When hovering over the logo, it turns white and becomes visible.

**To Reproduce:**

1. Go to 'nav page'
2. Click on 'hover the GitHub button'

**Expected Behavior:**
The GitHub logo should be visible against the background color without requiring user interaction.

**Screenshots:**

![git](https://github.com/sd012gfhkhhvh/Slate.AI/assets/65008142/8fd72f9f-1cff-4cc0-87d8-68a9ae47a47c)

**Environment (please complete the following information):**
- OS:  Windows 11
- Browser: Chrome
- Version: 120.0.6099.217

**Comment by sd012gfhkhhvh** [comment]
@pranay911 someone is working on the entire UI thing so this issue is already been resolved there. If you like the project and wanna contributre kindly raise another valid issue.

**Comment by sd012gfhkhhvh** [comment]
Closing the issue #13 as it is not applicable in the current context.
