### ISSUE TITLE
Enhancing the UI of the landing page and fixing UI in room page

### ISSUE THREAD

**Issue by 0xMishra** [sd012gfhkhhvh/Slate.AI#16]
- [x]  I agree to follow this project's Contributing Guidelines.

# UI enhancement of landing page
## The current landing page does not match the theme colors of the site like in the join room.
![Screenshot 2024-01-18 065646](https://github.com/sd012gfhkhhvh/Slate.AI/assets/76939349/9e52bf63-301b-402b-92ef-a9fea99233a8)

**Describe the Solution You'd Like:**
I am proposing a rebuild of the UI for the current landing page based on the theme colors of the site. We already have the color schemes finalized which have been used in the Join Room Page also.
![image](https://github.com/sd012gfhkhhvh/Slate.AI/assets/76939349/7abee754-63db-4af6-aeb4-d400b8e4dcbf)

After the Update, the UI will be responsive and it will match the color scheme of the site

# Fixing the UI on the room page
## Some issues with the UI on the room page need to be fixed

1. The tools section is taking too much space than required which needs to be fixed and the canvas should acquire more space.
2.  Apart from that the chat popup box should not have a scrollbar
![Screenshot 2024-01-18 233329](https://github.com/sd012gfhkhhvh/Slate.AI/assets/76939349/843f7721-1cd9-4808-a5a7-0a32994eca49)

**Comment by 0xMishra** [comment]
Please assign me this issue under JWOC

**Comment by sd012gfhkhhvh** [comment]
@mishra811  exclude such type of files marked in the image below next time when you are creating an pr.

![1](https://github.com/sd012gfhkhhvh/Slate.AI/assets/91667720/5bfb622a-8d66-4ac1-b786-cfc50dee338e)

**Comment by sd012gfhkhhvh** [comment]
issue #16 has been resolved and pr#17 got merged into dev
