### ISSUE TITLE
[FEATURE] - Request for Eraser Resize Feature in Slate AI

### ISSUE THREAD

**Issue by JavidSumra** [sd012gfhkhhvh/Slate.AI#18]
- [x]  I agree to follow this project's Contributing Guidelines.

**Is your feature request related to a problem? Please describe:**
Currently, the eraser tool in Slate AI has a fixed size, which can be limiting in various editing scenarios. Users may find it frustrating when they need to perform detailed edits requiring a smaller eraser size or cover larger areas with a broader stroke using a larger eraser. The lack of a resizable eraser feature hinders the customization and efficiency of the editing process.

**Describe the Solution You'd Like:**
I would like to request the addition of a resizable eraser feature in Slate AI. This feature should allow users to dynamically adjust the size of the eraser tool to better suit their editing needs. The implementation could include a user-friendly interface, such as a resizable eraser icon in the toolbar or a dedicated section for eraser settings. Users should be able to manually input the desired size or use interactive methods like drag-and-drop or a slider for quick adjustments.

**Describe Alternatives You've Considered:**
One alternative solution could be to provide preset eraser sizes that users can choose from. However, this might not offer the same level of flexibility as a resizable eraser feature, as users have varying preferences and editing requirements.

**Comment by JavidSumra** [comment]
Hey I Would Like to work on this issue under JWOC 2024.

**Comment by sd012gfhkhhvh** [comment]
@JavidSumra assigned you the issue.  Are you planning for  a dropdown or a slider? keep me updated how you are handling the issue.

**Comment by sd012gfhkhhvh** [comment]
issue#18 has been resolved under pr#22 and merged sucsessfully.
