### ISSUE TITLE
[BUG] - Button Switching Issue in Room-page: People and Chat Bar Interaction Problem

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#2]
### Description
The "Room chat" and the "People online" bar are not switching while pressing the respective buttons. In the Room-page, the two utility buttons at the bottom right corner, "People" and "Chat," are not interchangeably switching with each other. After opening either of the People or Chat pages, the other button stops working until I close the page.

### Steps to Reproduce
1. Go to the Room-page.
2. Attempt to switch between "People" and "Chat" by pressing the respective buttons.
3. Observe that the switching functionality is not working as expected.

### Screenshorts
![utility button bug](https://github.com/sd012gfhkhhvh/Slate.AI/assets/91667720/626392f7-cdd6-4d13-bcb2-412b7ad968e6)

### Expected Behavior
The "Room chat" and "People online" bar should switch seamlessly when pressing the respective buttons, allowing users to navigate between them without issues.

**Environment **
- OS: Windows 11
- Browser:  Chrome, Firefox

**Comment by sajid-31** [comment]
I would like to work on this issue under JWOC.

**Comment by sajid-31** [comment]
I just had to make a minor change on the onClick Event of both buttons in the index.jsx file in RoomPage

**CODE**
![Screenshot 2024-01-14 232938](https://github.com/sd012gfhkhhvh/Slate.AI/assets/114467202/206fd8f3-5931-4980-8757-94297a924ffa)

**WORKING VIDEO**

https://github.com/sd012gfhkhhvh/Slate.AI/assets/114467202/60b72166-833e-4aac-a299-4b4e0b3a7d3a

**Comment by sd012gfhkhhvh** [comment]
Well done @sajid-31 , It seems to be a good working solution. But you need to comment on this issue again as u commented before 15th  jan. Comment and I will assign you the issue. Make sure to keep the main branch sync with your changes before creating an pr. Follow the contributing.md for details

**Comment by sajid-31** [comment]
I would like to work on this issue under JWOC.

This is my first PR, I will try to do it myself, but if i face any problem I'll message on discord.

**Comment by sd012gfhkhhvh** [comment]
> I would like to work on this issue under JWOC.
> 
> This is my first PR, I will try to do it myself, but if i face any problem I'll message on discord.

sure @sajid-31  go ahead. assigning you the issue. discuss with me before making any pr

**Comment by sd012gfhkhhvh** [comment]
issue #2 fixed and merged with no conflicts.
