### ISSUE TITLE
[FEATURE] - Store the Room chats locally in the browser.

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#21]
- [x]  I agree to follow this project's Contributing Guidelines.

**Is your feature request related to a problem? Please describe:**
The room chats are volatile, it vanishes when the chatbox closes.. It is not a desired behaviour of a room chat. The chats history should be there untill a user got disconnected or leaves the room.

**Describe the Solution You'd Like:**
Use local storage of the browser to store the chats for a session. Once the user got disconnected the chats should be gone even if he rejoins.

**Comment by JavidSumra** [comment]
I Would Like to Work on this Issue Under JWOC 2024

**Comment by JavidSumra** [comment]
Hello @sd012gfhkhhvh, could you please provide more details about this feature? From my understanding, it involves persisting messages, and when a user leaves the room, the messages need to be erased. Is that correct?

**Comment by sd012gfhkhhvh** [comment]
issue#21 has been resolved and pr#24 got merged successfully
