### ISSUE TITLE
[BUG] - Room with no name and room code

### ISSUE THREAD

**Issue by AntonyJudeShaman** [sd012gfhkhhvh/Slate.AI#23]
- [x]  I agree to follow this project's Contributing Guidelines.

**Severity:**
-  Major

**Describe the Bug:**
A room with no name and code can be created and another user can join this empty room without entering any credentials(room code). 

**To Reproduce:**

1. Go to 'Create room page'
2. Click on 'Generate room' with name and code empty. You will be redirected to the '/' path. go back to create room page and wait.
3. Open another browser and go to create room and click generate room with all fields empty.
4. Quickly go back to the browser in step 2 to see a message that a null user has joined the room.

**Screenshots:**
![image](https://github.com/sd012gfhkhhvh/Slate.AI/assets/105967620/1fe481da-d1f3-4e34-80f2-dcb6739fc5e5)
![image](https://github.com/sd012gfhkhhvh/Slate.AI/assets/105967620/4fdfb3ff-6609-4e34-b258-e19f031c298a)

**Environment (please complete the following information):**
- OS: Windows 11
- Browser: Chrome
- Version: latest

**Comment by AntonyJudeShaman** [comment]
i would like to work on this issue @sd012gfhkhhvh 
from JWOC

**Comment by sd012gfhkhhvh** [comment]
@AntonyJudeShaman It's a potential bug to work on. Go ahead.
I will suggest you do a client side schema validation before generating or joining a room for now as we are not using any db for storing any room data.
