### ISSUE TITLE
[Bug] - Messages Are Visible to All Rooms

### ISSUE THREAD

**Issue by JavidSumra** [sd012gfhkhhvh/Slate.AI#28]
Certainly! Here is a template for the issue you'd like to open:

---

### Bug Report

- [x]  I agree to follow this project's Contributing Guidelines.

**Is your feature request related to a problem? Please describe:**
When messaging in a room on Slate.AI, the messages are visible to all other rooms, which seems to be unintended behavior.

**Describe the Solution You'd Like:**
I would like the messaging feature to be room-specific so that messages in one room are not visible in other rooms. Each room's messages should be isolated and private to that specific room.

**Describe Alternatives You've Considered:**
An alternative solution could be implementing a toggle option for users to choose whether they want their messages to be visible across all rooms or restricted to the specific room they are in.

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Sir I Would Like to Work on This Issue under JWOC 2024.

**Comment by sd012gfhkhhvh** [comment]
issue #28 has been resolved and pr #30 has been merged into dev
