### ISSUE TITLE
[Bug] - Update Readme file

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#29]
- [x]  I agree to follow this project's Contributing Guidelines.

**Is your feature request related to a problem? Please describe:**
Update the readme file with the snapshots of the updated UI of our application. 

**Describe the Solution You'd Like:**
Replace the old snapshots and add new snapshots but deleting the old ones. 

**Additional Context:**
NB: make sure you keep the names of the new snapshot exactly the same as the deleted snapshots .
(deleted)xyz.png ---> (new)xyz.png
Do not delete other images except the substitute of the old ones.

**Comment by Surajit0573** [comment]
Assign this to me under JWOC 2024

**Comment by sd012gfhkhhvh** [comment]
> Assign this to me under JWOC 2024

assigned. Go ahead

**Comment by sd012gfhkhhvh** [comment]
@Surajit0573 put screen-shots/video of the readme in the comment box.
