### ISSUE TITLE
[Bug] - While Refresh The Page Participants Left Room 

### ISSUE THREAD

**Issue by JavidSumra** [sd012gfhkhhvh/Slate.AI#31]
### Bug Report

- [x]  I agree to follow this project's Contributing Guidelines.

**Is your feature request related to a problem? Please describe:**
When I refresh the page on Slate.AI, I am unexpectedly leaving the room. This behavior is not anticipated, and it disrupts the user experience.

**Describe the Solution You'd Like:**
I would like the system to remember the current room a user is in and retain that information even after a page refresh. The user should not be automatically removed from the room upon refreshing the page.

**Describe Alternatives You've Considered:**
An alternative solution could be implementing a session persistence mechanism that stores the user's current room information, allowing them to rejoin the room after a page refresh.

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Sir I Would Like to Work on This Issue Under JWOC 2024

**Comment by sd012gfhkhhvh** [comment]
> Hey @sd012gfhkhhvh Sir I Would Like to Work on This Issue Under JWOC 2024

Bro you did choose the wrong template for a bug. Please keep this in mind next time. 

What approach you are thingking? Is it a session storage or urlParam or is it a state management library?

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Sir Please Close This Issue

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Sir Please Check the Latest PR for this Issue.

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Sir Please Check the Latest PR for this Issue.

**Comment by sd012gfhkhhvh** [comment]
issue #31 has been resolved and merged under pr #32
