### ISSUE TITLE
[BUG] - Tool strokes are visible to all rooms

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#33]
- [x]  I agree to follow this project's Contributing Guidelines.

**Severity:**
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

**Describe the Bug:**
Tool strokes are visible to other rooms.

**To Reproduce:**
create different rooms and perform draw operations.

**Environment (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version Latest

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Sir I would like to Work on this issue under JWOC 2024

**Comment by sd012gfhkhhvh** [comment]
issue #33 has been resolved and pr#34 has been merged into dev
