### ISSUE TITLE
[FEATURE] - Show unread message count on chat button

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#36]
- [x]  I agree to follow this project's Contributing Guidelines.

**Is your feature request related to a problem? Please describe:**
 In the whiteboard page there is no notification system for incoming messages while the chat box is closed. User is unaware about the incoming messages while doing other stuff in the room. Its leads to a bad user experience. 

**Describe the Solution You'd Like:**
 It is suggested to implement a unread message count bubble (like whatsapp has) on the chat box button in the room page. No need to notify via toast each time a message has come, just show the unread count on the button.

![Screenshot 2024-02-17 000231](https://github.com/sd012gfhkhhvh/Slate.AI/assets/91667720/58a8d863-d196-40d8-b53f-0c57113fadee)

**Comment by Anushkabh** [comment]
Kindly assign me this issue under JWOC @sd012gfhkhhvh

**Comment by sd012gfhkhhvh** [comment]
> Kindly assign me this issue under JWOC @sd012gfhkhhvh

keep me updated with your implementation

**Comment by Anushkabh** [comment]
yes sure @sd012gfhkhhvh

**Comment by Anushkabh** [comment]
kindly merge my pr @sd012gfhkhhvh  #43

**Comment by sd012gfhkhhvh** [comment]
> kindly merge my pr @sd012gfhkhhvh #43

Will merger after review

**Comment by Anushkabh** [comment]
kindly merge the pr #45 if satisfied @sd012gfhkhhvh

**Comment by sd012gfhkhhvh** [comment]
> kindly merge the pr #45 if satisfied @sd012gfhkhhvh

It has some inconsistencies , some edge cases should be handled. 
I am merging for now, if you are interested you can contribute to it after the JWOC event also

**Comment by sd012gfhkhhvh** [comment]
issue resolved under PR #45

**Comment by Anushkabh** [comment]
@sd012gfhkhhvh  yes i would fix this.. thankyou

**Comment by sd012gfhkhhvh** [comment]
> @sd012gfhkhhvh yes i would fix this.. thankyou

ping me up with your full name, githubId,college name etc on discord to keep track of contributors in phase-2
