### ISSUE TITLE
[FEATURE] - Add a loading animation while creating/joining a room

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#37]
- [x]  I agree to follow this project's Contributing Guidelines.

**Is your feature request related to a problem? Please describe:**
The room creation/joining is almost instant as the load on the server in minimal for now. But when the load goes up or by means of any failure it will show white screen to the user which leads to bad user experience.

**Describe the Solution You'd Like:**
Add an artificial delay of max 3 seconds to show the implemented loading screen.

**Referance**
Refer to the joining animation of google meet while creating/joining a room and implement similar kind of effect.

**Additional Context:**

**Comment by ramith-kulal** [comment]
would like to work on this under jwoc

**Comment by sd012gfhkhhvh** [comment]
issue #37 has been resolved and PR #44 has been merged into dev
