### ISSUE TITLE
[FEATURE] - Add touch support for mobile devices

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#39]
- [x]  I agree to follow this project's Contributing Guidelines.

**Is your feature request related to a problem? Please describe:**
The current version of the app does not support drawing via touch.

**Describe the Solution You'd Like:**
 Add touch support along with mouse pointer for drawing in the canvas.

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Sir I would like to Work on this issue under JWOC 2024

**Comment by sd012gfhkhhvh** [comment]
@JavidSumra are you still working on issue #3 ?

**Comment by JavidSumra** [comment]
Yeah @sd012gfhkhhvh Sir
