### ISSUE TITLE
[FEATURE] - Implement an eraser tool in the toolbar

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#6]
# Feature Request

- [x] I agree to follow this project's Contributing Guidelines.

## Proposed Solution

Implement an eraser tool in the toolbar on the room page to allow users to clean a particular part of the board.

## Implementation Steps:
1.  Refer to the roughjs API doccumentation - https://github.com/rough-stuff/rough/wiki
2.  Follow the coding style used to implement other tools and structure your jsx accordingly
3.  Implement inside a seperate div inside toolbar seperate from the drawing tools.
4.  Go through the entire implementation process of other tools both frontend and the connection with socket io carefully.
5.  Add the frontend implementation.
6.   Connect with backend using event emmitor of socket.io on server.js file
7.  Test your changes and push to github

**Expected Outcome:**
 A eraser tool Should be there inside the tool bar

**Comment by JavidSumra** [comment]
I would like to work on that issue under JWOC

**Comment by sd012gfhkhhvh** [comment]
Go ahead @JavidSumra . keep me updated with your changes. Feel free to communucate with me before making any pr.

**Comment by sd012gfhkhhvh** [comment]
issue #6 resolved and sucsessfully merged into dev
