### ISSUE TITLE
[BUG] - Remove the background image from roompage and join room page

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#7]
- [x]  I agree to follow this project's Contributing Guidelines.

**Severity:**
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

**Describe the Bug:**
 The background image in the landing page is implemented thoughout the entire site. This is a bug. We don't want the background image to be present in the Join room and room page. We want it only in the landing page.

**To Reproduce:**
-  Go to the site's landing page 
-  click start whiteboarding  see the background
-  click create or join room see the background

**Expected Behavior:**
The background image should be present only on the landing page.

**Screenshots:**
- Join Room Page
![join room page](https://github.com/sd012gfhkhhvh/Slate.AI/assets/91667720/79066bd3-8d51-4c93-aeb3-8480e488642e)

- Room Page
![Screenshot 2024-01-14 040505](https://github.com/sd012gfhkhhvh/Slate.AI/assets/91667720/b4e98183-6985-4d8f-9b53-6db4f6f63676)

**Environment**
- OS: Windows 11
- Browser:  Chrome, Firefox

**Comment by Divyanshgarg-04** [comment]
Do we need to remove the whole background image or the background image inside the canvas.

**Comment by sd012gfhkhhvh** [comment]
> Do we need to remove the whole background image or the background image inside the canvas.

remove the whole background. The background should only be present in the landing page. If you can find for attractive background let me know. 

If you wanna work on that issue pls follow the jwoc guideline and comment "'I would like to work on that issue under JWOC" otherwise they did not count your contribution.

**Comment by Divyanshgarg-04** [comment]
@sd012gfhkhhvh I would like to work on that issue under JWOC. Please assign this issue to me after JWOC start

**Comment by Anushkabh** [comment]
i would like to work on this .. kindly assign @sd012gfhkhhvh

**Comment by rahul200367** [comment]
I would like to work on that issue under JWOC.

**Comment by sd012gfhkhhvh** [comment]
@Divyanshgarg-04  and @Anushkabh  kindly go through the discord announcement chanel. You both did some mistake while commenting on the issue. Some of u did before 15th jan and other did not mention jwoc in their comment.

So as per rule @rahul200367  will be assignned the issue. Plese visit the slateai chanel in the discord and do the steps i mentioned in the pinned message in the chanel after i assigned U the issue

**Comment by sd012gfhkhhvh** [comment]
@rahul200367 keep me updated with your changes through snap shorts of your changes. Try to finish it By today as it is a very small issue.

**Comment by rahul200367** [comment]
done ..
![login form](https://github.com/sd012gfhkhhvh/Slate.AI/assets/114770156/83bbcd24-f9e2-4125-b7a1-3219f34af943)
![Uploading canvas.png…]()

**Comment by sd012gfhkhhvh** [comment]
@rahul200367 the canvas image is not uploaded properly. also add the landing page image and the code snap-shot of your changes.

**Comment by rahul200367** [comment]
![canvas](https://github.com/sd012gfhkhhvh/Slate.AI/assets/114770156/3d96e1c0-dfcb-4df1-84ef-3e80394c3b69)
. i have change background css path from home page to room page
![change in code](https://github.com/sd012gfhkhhvh/Slate.AI/assets/114770156/d6f289c7-ccc6-4175-a207-e14eaad7ff90)

**Comment by sd012gfhkhhvh** [comment]
But the background is still in the Room page.

**Comment by rahul200367** [comment]
okay i will remove background whole.. 
![bkg up](https://github.com/sd012gfhkhhvh/Slate.AI/assets/114770156/81f7381a-d07d-4f81-85c8-152c575384c9)

**Comment by 0xMishra** [comment]
Can you please assign this issue to me under JWOC

**Comment by sd012gfhkhhvh** [comment]
@rahul200367 as you are not responding for a while I am assigning it to someone else.

**Comment by sd012gfhkhhvh** [comment]
@mishra811 assigned You the issue

**Comment by sd012gfhkhhvh** [comment]
Issue #7 has been sucessfully merged
