### ISSUE TITLE
[FEATURE] - Enhance the UI of the Join Room page

### ISSUE THREAD

**Issue by sd012gfhkhhvh** [sd012gfhkhhvh/Slate.AI#8]
- [x]  I agree to follow this project's Contributing Guidelines.

### Description
The current style of the join room page is old fashioned, make it more attractive.

### Proposed Solution
Use tailwind css and other UI library/framwork (e.g. mui) of your own choice.

### Screenshort
![join room page](https://github.com/sd012gfhkhhvh/Slate.AI/assets/91667720/0a3c7914-de37-4b9e-92ec-e09e3554a6d2)

**Comment by 0xMishra** [comment]
Can you please assign me this issue under JWOC

**Comment by sd012gfhkhhvh** [comment]
> Can you please assign me this issue under JWOC

Yup @mishra811 , you will be assigned the issue. first tell me your thoughts regarding the UI enhancement, how u wanna tackle the issue?

**Comment by 0xMishra** [comment]
I am thinking of building it with tailwind css. Instead of showing both these forms alongside, I want to dynamically render the forms by  a button press.

**Comment by sd012gfhkhhvh** [comment]
> I am thinking of building it with tailwind css. Instead of showing both these forms alongside, I want to dynamically render the forms by a button press.

sounds good. assigning you the issue , keep me updated with your changes in the comment section with some snap shots. Now go to the slateai chanel in the discord and see the pinned message and do the action mentioned.

**Comment by mishra811** [comment]
Hello, I am almost done with the UI. Please look a these screenhots and let me know what you think about it.

1. Mobile view
![Screenshot 2024-01-15 200151](https://github.com/sd012gfhkhhvh/Slate.AI/assets/76939349/42661b5f-5d2f-4b5a-85db-2dd0011c01d6)

2. Tablet view
![Screenshot 2024-01-15 200103](https://github.com/sd012gfhkhhvh/Slate.AI/assets/76939349/8cb5bf8a-47f2-462e-84c9-61389a1a60c3)

3. Desktop view
![Screenshot 2024-01-15 200838](https://github.com/sd012gfhkhhvh/Slate.AI/assets/76939349/8025b4f3-6066-44ce-ac59-f177b0ed6c48)

**Comment by sd012gfhkhhvh** [comment]
isue#8 has been resolved.
pr#12 has been sucessfully merged.
